spring:
  graphql:
    graphiql:
      enabled: true
  profiles:
    active: dev
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/discord_db
    username: postgres
    password: postgres
server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/discord_db
    username: postgres
    password: postgres
server:
  port: 8080