### register
POST http://localhost:{{port}}/{{prefix}}/auth/register
Content-Type: application/json

{
  "email": "admin@admin.com",
  "username": "admin.admin",
  "password": "adminpassword",
  "firstName": "firstName",
  "lastName": "lastName"
}

### login
POST http://localhost:{{port}}/{{prefix}}/auth/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "adminpassword"
}

### test
GET http://localhost:{{port}}/
Content-Type: application/json
Authorization: Bearer {{token}}